config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {registrations: "users/registrations",
                                   sessions: "users/sessions"}

  root "static_pages#index"

  get 'profile/:id', to: 'users#profile', as: 'profile'
  get 'user/:id', to: 'users#show', as: 'user'
  get 'about', to: 'static_pages#about', as: 'static_pages/about'

  resources :news do
    resources :news_comments
  end
  resources :forums do
    resources :forum_comments
  end
  resources :articles do
    resources :article_comments
  end

  #resources :users

  resources :rooms do
    resources :messages
  end


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord

  has_one_attached :avatar
  has_many_attached :images

  belongs_to :user
  has_and_belongs_to_many :categories
  has_many :article_comments

  default_scope -> { order(created_at: :desc) }

  STATUS=[:passive, :active]

  validates :title, :body, presence: true


end

app/models/article_comment.rb
class ArticleComment < ApplicationRecord
  belongs_to :user
  belongs_to :article
end

app/models/category.rb
class Category < ApplicationRecord

  has_and_belongs_to_many :news
  has_and_belongs_to_many :forums
  has_and_belongs_to_many :articles

end

app/models/forum.rb
class Forum < ApplicationRecord

  has_one_attached :avatar

  belongs_to :user
  has_and_belongs_to_many :categories
  has_many :forum_comments

  default_scope -> { order(created_at: :desc) }

  STATUS=[:passive, :active]

  validates :title, :body, presence: true

  #validates :status, inclusion: {in: Forum::STATUS}
end

app/models/forum_comment.rb
class ForumComment < ApplicationRecord
  belongs_to :user
  belongs_to :forum
end

app/models/message.rb
class Message < ApplicationRecord

  belongs_to :user
  belongs_to :room

  after_create_commit {broadcast_append_to room}

  before_create :confirm_participant

  def confirm_participant
    return unless room.is_private
    is_participant = Participant.where(user_id: self.user.id, room_id: self.room.id).first
    throw :abort unless is_participant
  end

end

app/models/news.rb
class News < ApplicationRecord

  has_one_attached :avatar

  belongs_to :user
  has_and_belongs_to_many :categories
  has_many :news_comments

  default_scope -> { order(created_at: :desc) }

  validates :title, :body, presence: true

end

app/models/news_comment.rb
class NewsComment < ApplicationRecord
  belongs_to :user
  belongs_to :news
end

app/models/participant.rb
class Participant < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/room.rb
class Room < ApplicationRecord

  validates_uniqueness_of :name
  scope :public_rooms,->{where(is_private: false)}
  after_create_commit {broadcast_if_public}

  has_many :messages
  has_many :participants, dependent: :destroy



  def broadcast_if_public
    broadcast_append_to "rooms" unless self.is_private
  end

  def self.create_private_room(users, room_name)
    single_room = Room.create(name: room_name, is_private: true)
    users.each do |user|
      Participant.create(user_id: user.id, room_id: single_room.id)
    end
    single_room
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :avatar

  has_many :news
  has_many :forums
  has_many :articles
  has_many :article_comments
  has_many :news_comments
  has_many :forum_comments
  has_many :messages

  scope :all_except,->(user){where.not(id: user)}

  after_create_commit {broadcast_append_to "users"}

  def name_last_name
    "#{name} #{last_name}"
  end

  WORKGROUP=["User", "Moderator", "Admin"]
  GENDER=["Male", "Female"]

end

app/controllers/news_controller.rb
class NewsController < ApplicationController

  before_action :set_news, only: %i[show edit update destroy]

  def index
    @search = News.ransack(params[:q])
    @news = @search.result(distinct: true)
  end

  def show
  end

  def new
    @new = News.new
  end

  def create
    @new = current_user.news.build(news_params)
    if @new.save
      redirect_to news_path(@new), notice: "News was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @new.update(news_params)
      redirect_to news_path(@new), notice: "News was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @new.destroy
    redirect_to news_index_path, status: :see_other, notice: "News was successfully destroyed."
  end

  private

  def news_params
    params.require(:news).permit(:title, :body, :avatar, category_ids:[])
  end

  def set_news
    @new = News.find(params[:id])
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController

  before_action :authenticate_user!

  def index
    @room = Room.new
    @rooms = Room.public_rooms
    @users = User.all_except(current_user)

    render "index"
  end

  def show
    @single_room = Room.find(params[:id])
    @room = Room.new
    @rooms = Room.public_rooms
    @message = Message.new
    @messages = @single_room.messages.order(create_at: :asc)
    @users = User.all_except(current_user)

    render "index"
  end

  def create
    @room = Room.create(name: params["room"]["name"])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController


  def show
    @user = User.find(params[:id])
    @users = User.all_except(current_user)

    @room = Room.new
    @rooms = Room.public_rooms
    @room_name = get_name(@user, current_user)

    @single_room = Room.where(name: @room_name).first || Room.create_private_room([@user, current_user], @room_name)

    @message = Message.new
    @messages = @single_room.messages.order(create_at: :asc)

    render "rooms/index"
  end

  def profile
    @user = User.find(params[:id])
  end

  private

  def get_name(user1, user2)
    user = [user1, user2].sort
    "private_#{user[0].id}_#{user[1].id}"
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/forums_helper.rb
module ForumsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/news_comments_helper.rb
module NewsCommentsHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/news/_form.html.erb
<%= form_with model: @new do |n| %>

  <%= render 'static_pages/errors', object: @new %>

  <div>
    <div>
      <%= n.label :title %>
    </div>
    <div>
      <%= n.text_field :title, class: "form-control" %>
    </div>
  </div>
  <div>
    <div>
      <%= n.label :body %>
    </div>
    <div>
      <%= n.text_field :body, class: "form-control" %>
    </div>
  </div>
  <div>
    <%= n.label :avatar %>
    <%= n.file_field :avatar %>
  </div>
  <div>
    <%= n.label :category %>
    <%= n.collection_check_boxes :category_ids, Category.all, :id, :name do |c| %>
      <div class="collection-check-box">
        <%= c.check_box %>
        <%= c.label %>
      </div>
    <% end %>
  </div>
  <%= n.submit "Submit" %>
<% end %>

app/views/news/edit.html.erb
<%= render "news/form" %>

app/views/news/index.html.erb
<%= render "static_pages/search" %>

<% @news.each do |n| %>
  <% if n.avatar.attached? %>
    <p><%= image_tag n.avatar, width: "200px" %></p>
  <% end %>
  <p><%= n.title %></p>
  <p><%= n.body %></p>
  <p><%= n.user_id %></p>
  <p><%= n.categories.map(&:name).sort.join(", ") %></p>
  <p><%= link_to "Show", news_path(n) %></p>
  <p><%= link_to "Edit", edit_news_path(n) %></p>
  <p><%= link_to "Delete", news_path(n), data: {"turbo-method": :delete,
                                                turbo_confirm: "You sure?"} %></p>
<% end %>

<%= link_to "New", new_news_path %>

app/views/news/new.html.erb
<%= render "news/form" %>

app/views/news/show.html.erb
<% if @new.avatar.attached? %>
  <p><%= image_tag @new.avatar, width: "200px" %></p>
<% end %>
<p><%= @new.title %></p>
<p><%= @new.body %></p>
<p><%= @new.user_id %></p>
<p><%= @new.categories.map(&:name).sort.join(", ") %></p>
<p><%= link_to "Edit", edit_news_path(@new) %></p>
<p><%= link_to "Delete", news_path(@new), data: {"turbo-method": :delete,
                                                        turbo_confirm: "You sure?"} %></p>
<p><%= link_to "Back", :back %></p>

<%= render "news_comments/form" %>

app/views/rooms/_new_room_form.html.erb
<%= form_with(model: @room, remote: true) do |f| %>
  <%= f.text_field :name, class: "border text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 bg-gray-700
  border-gray-600 placeholder-gray-400 text-white", placeholder: "New Room", autocomplete: 'off' %>
  <% f.submit data:{disable_with: false} %>
<% end %>

app/views/rooms/_room.html.erb
<div class="px-5 py-4   flex items-center   cursor-pointer border-l-4 border-l-transparent hover:bg-slate-100">
  <%= link_to(room_path(room), class:"flex items-center p-2 text-base font-normal rounded-lg") do %>
    <div class="ml-4">
      <p class="text-md font-semibold m-0 p-0"><%= room.name %></p>
    </div>
  <% end %>
</div>

app/views/rooms/index.html.erb
<script src="//unpkg.com/alpinejs" defer></script>
<div class="p-5 h-screen w-full">
  <div class=" h-full overflow-hidden flex flex-col rounded-xl overflow-hidden shadow-xl bg-gray-700 text-gray-400">
    <div class="h-full flex">
      <div class="h-full w-96 border-r flex flex-col">
        <div class="h-full overflow-x-auto overflow-scroll">
          <h1 class="px-4 pt-4 pb-2 border-b-4 border-b-blue-500 text-lg font-semibold text-gray-400 uppercase">Users</h1>
          <%= turbo_stream_from "users" %>
          <div id="users">
            <%= render @users %>
          </div>
          <h1 class="px-4 pt-4 pb-2 border-b-4 border-b-blue-500 text-lg font-semibold text-gray-400 uppercase">Rooms</h1>
          <div class="mt-5 w-full flex justify-center">
            <%= render "rooms/new_room_form" %>
          </div>
          <%= turbo_stream_from "rooms" %>
          <div id="rooms">
            <%= render @rooms %>
          </div>
        </div>
      </div>
      <div class="w-full h-full flex flex-col">
        <% if @single_room %>
          <div class="h-16 border-b-4 border-b-blue-500 flex justify-between items-center w-full px-5 py-2 shadow-sm">
            <div id="single_room" class="flex items-center">
              <% if @user %>
                <% if @user.avatar.attached? %>
                  <%= image_tag @user.avatar, class: "h-10 w-10 overflow-hidden rounded-full"%>
                <% else %>
                  <img class= "h-10 w-10 overflow-hidden rounded-full" src="https://st2.depositphotos.com/47577860/46283/v/450/depositphotos_462836132-stock-illustration-assassin-deadpool-face-icon.jpg" alt="">
                <% end %>
              <% end %>
              <p class="font-semibold ml-3 text-gray-400"><%= @user&.name_last_name || @single_room.name %></p>
            </div>
          </div>
          <div class="h-full px-10 py-4 overflow-x-auto overflow-scroll">
            <%= turbo_stream_from @single_room %>
            <div id="messages">
              <%= render @messages %>
            </div>
          </div>
          <%= render "messages/new_message_form" %>
        <% end %>
      </div>
    </div>
  </div>
</div>