config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {registrations: "users/registrations",
                                   sessions: "users/sessions"}

  root "static_pages#index"

  get 'profile/:id', to: 'users#profile', as: 'profile'
  get 'user/:id', to: 'users#show', as: 'user'
  get 'about', to: 'static_pages#about', as: 'static_pages/about'

  resources :news do
    resources :news_comments
  end
  resources :forums do
    resources :forum_comments
  end
  resources :articles do
    resources :article_comments
  end

  #resources :users

  resources :rooms do
    resources :messages
  end


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord

  has_one_attached :avatar
  has_many_attached :images

  belongs_to :user
  has_and_belongs_to_many :categories
  has_many :article_comments

  default_scope -> { order(created_at: :desc) }

  STATUS=[:passive, :active]

  validates :title, :body, presence: true


end

app/models/article_comment.rb
class ArticleComment < ApplicationRecord
  belongs_to :user
  belongs_to :article
end

app/models/category.rb
class Category < ApplicationRecord

  has_and_belongs_to_many :news
  has_and_belongs_to_many :forums
  has_and_belongs_to_many :articles

end

app/models/forum.rb
class Forum < ApplicationRecord

  has_one_attached :avatar

  belongs_to :user
  has_and_belongs_to_many :categories
  has_many :forum_comments

  default_scope -> { order(created_at: :desc) }

  STATUS=[:passive, :active]

  validates :title, :body, presence: true

  #validates :status, inclusion: {in: Forum::STATUS}
end

app/models/forum_comment.rb
class ForumComment < ApplicationRecord
  belongs_to :user
  belongs_to :forum
end

app/models/message.rb
class Message < ApplicationRecord

  belongs_to :user
  belongs_to :room

  after_create_commit {broadcast_append_to room}

  before_create :confirm_participant

  def confirm_participant
    return unless room.is_private
    is_participant = Participant.where(user_id: self.user.id, room_id: self.room.id).first
    throw :abort unless is_participant
  end

end

app/models/news.rb
class News < ApplicationRecord

  has_one_attached :avatar

  belongs_to :user
  has_and_belongs_to_many :categories
  has_many :news_comments

  default_scope -> { order(created_at: :desc) }

  validates :title, :body, presence: true

end

app/models/news_comment.rb
class NewsComment < ApplicationRecord
  belongs_to :user
  belongs_to :news
end

app/models/participant.rb
class Participant < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/room.rb
class Room < ApplicationRecord

  validates_uniqueness_of :name
  scope :public_rooms,->{where(is_private: false)}
  after_create_commit {broadcast_if_public}

  has_many :messages
  has_many :participants, dependent: :destroy



  def broadcast_if_public
    broadcast_append_to "rooms" unless self.is_private
  end

  def self.create_private_room(users, room_name)
    single_room = Room.create(name: room_name, is_private: true)
    users.each do |user|
      Participant.create(user_id: user.id, room_id: single_room.id)
    end
    single_room
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :avatar

  has_many :news
  has_many :forums
  has_many :articles
  has_many :article_comments
  has_many :news_comments
  has_many :forum_comments
  has_many :messages

  scope :all_except,->(user){where.not(id: user)}

  after_create_commit {broadcast_append_to "users"}

  def name_last_name
    "#{name} #{last_name}"
  end

  WORKGROUP=["User", "Moderator", "Admin"]
  GENDER=["Male", "Female"]

end

app/controllers/news_controller.rb
class NewsController < ApplicationController

  before_action :set_news, only: %i[show edit update destroy]

  def index
    @search = News.ransack(params[:q])
    @news = @search.result(distinct: true)
  end

  def show
  end

  def new
    @new = News.new
  end

  def create
    @new = current_user.news.build(news_params)
    if @new.save
      redirect_to news_path(@new), notice: "News was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @new.update(news_params)
      redirect_to news_path(@new), notice: "News was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @new.destroy
    redirect_to news_index_path, status: :see_other, notice: "News was successfully destroyed."
  end

  private

  def news_params
    params.require(:news).permit(:title, :body, :avatar, category_ids:[])
  end

  def set_news
    @new = News.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/forums_helper.rb
module ForumsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_header.html.erb
<nav class="border-gray-200 px-2 md:px-4 py-2.5 bg-gray-900">
  <div class="flex flex-wrap justify-between items-center mx-auto max-w-screen-xl">
    <a href="#" class="flex items-center">
      <img src="https://flowbite.com/docs/images/logo.svg" class="mr-3 h-6 sm:h-9" alt="Flowbite Logo">
      <span class="self-center text-xl font-semibold whitespace-nowrap text-white">DOSI</span>
    </a>
    <div class="flex items-center md:order-2">
      <div>
        <%= link_to "Login", new_user_session_path, class: "text-white focus:ring-4 font-medium rounded-lg text-sm px-4 py-2 md:px-5 md:py-2.5 mr-1 md:mr-2 hover:bg-gray-700 focus:outline-none focus:ring-gray-800" %>
        <%= link_to "Sign up", new_user_registration_path, class: "text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm px-4 py-2 md:px-5 md:py-2.5 mr-1 md:mr-2 dark:bg-blue-600 dark:hover:bg-blue-700 focus:outline-none dark:focus:ring-blue-800" %>
      </div>
    </div>
    <div id="mega-menu-icons" class="hidden justify-between items-center w-full md:flex md:w-auto md:order-1">
      <ul class="flex flex-col mt-4 text-sm font-medium md:flex-row md:space-x-8 md:mt-0">
        <li>
          <%= link_to "News", news_index_path, class: "block py-2 pr-4 pl-3 border-b md:hover:bg-transparent md:border-0 md:hover:text-blue-500 md:p-0 text-gray-400 hover:bg-gray-700 border-gray-700" %>
        </li>
        <li>
          <%= link_to "Forum", forums_path, class: "block py-2 pr-4 pl-3 text-gray-400 border-b md:hover:bg-transparent md:border-0 md:hover:text-blue-500 md:p-0 hover:bg-gray-700 border-gray-700" %>
        </li>
        <li>
          <%= link_to "Articles", articles_path, class: "block py-2 pr-4 pl-3 text-gray-400 border-b md:hover:bg-transparent md:border-0 md:hover:text-blue-500 md:p-0 hover:bg-gray-700 border-gray-700" %>
        </li>
        <li>
          <%= link_to "Ratings", root_path, class: "block py-2 pr-4 pl-3 text-gray-400 border-b md:hover:bg-transparent md:border-0 md:hover:text-blue-500 md:p-0 hover:bg-gray-700 border-gray-700" %>
        </li>
        <li>
          <%= link_to "Investments", root_path, class: "block py-2 pr-4 pl-3 text-gray-400 border-b md:hover:bg-transparent md:border-0 md:hover:text-blue-500 md:p-0 hover:bg-gray-700 border-gray-700" %>
        </li>
        <li>
          <%= link_to "Financial calculator", root_path, class: "block py-2 pr-4 pl-3 text-gray-400 border-b md:hover:bg-transparent md:border-0 md:hover:text-blue-500 md:p-0 hover:bg-gray-700 border-gray-700" %>
        </li>
        <li>
          <%= link_to "Courses", root_path, class: "block py-2 pr-4 pl-3 text-gray-400 border-b md:hover:bg-transparent md:border-0 md:hover:text-blue-500 md:p-0 hover:bg-gray-700 border-gray-700" %>
        </li>
        <li>
          <%= link_to "Events", root_path, class: "block py-2 pr-4 pl-3 text-gray-400 border-b md:hover:bg-transparent md:border-0 md:hover:text-blue-500 md:p-0 hover:bg-gray-700 border-gray-700" %>
        </li>
        <li>
          <%= link_to "About us", static_pages_about_path, class: "block py-2 pr-4 pl-3 text-gray-400 border-b md:hover:bg-transparent md:border-0 md:hover:text-blue-500 md:p-0 hover:bg-gray-700 border-gray-700" %>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_sidebar.html.erb
<aside class="w-64" aria-label="Sidebar">
  <div class="overflow-y-auto py-4 px-3 rounded bg-gray-900">
    <div class="flex items-center pl-2 pt-2 pb-6 space-x-4 ">
      <% if current_user.avatar.attached? %>
        <%= image_tag current_user.avatar, class: "w-12 h-12 rounded-full dark:bg-gray-500" %>
      <% else %>
        <img class="w-12 h-12 rounded-full dark:bg-gray-500" src="https://st2.depositphotos.com/47577860/46283/v/450/depositphotos_462836132-stock-illustration-assassin-deadpool-face-icon.jpg" alt="">
      <% end %>
      <div>
        <h2 class="text-lg font-semibold text-white"><%= current_user.name %> <%= current_user.last_name %></h2>
        <span class="flex items-center space-x-1">
        <%= link_to "View profile", root_path, class: "text-xs hover:underline dark:text-gray-400" %>
			</span>
      </div>
    </div>
    <ul class="space-y-2">
      <li>
        <button type="button" class="flex items-center p-2 w-full text-base font-normal rounded-lg transition duration-75 group hover:bg-gray-700 text-white aria-controls="dropdown-example" data-collapse-toggle="dropdown-example">
        <svg aria-hidden="true" class="flex-shrink-0 w-6 h-6 text-gray-400 transition duration-75 group-hover:text-white" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path d="M2 10a8 8 0 018-8v8h8a8 8 0 11-16 0z"></path><path d="M12 2.252A8.014 8.014 0 0117.748 8H12V2.252z"></path></svg>
        <span class="flex-1 ml-3 text-left whitespace-nowrap" sidebar-toggle-item="">Investment portfolio</span>
        <svg sidebar-toggle-item="" class="w-6 h-6" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z" clip-rule="evenodd"></path></svg>
        </button>
        <ul id="dropdown-example" class="hidden py-2 space-y-2">
          <li>
            <%= link_to "#", root_path, class: "flex items-center p-2 pl-11 w-full text-base font-normal rounded-lg transition duration-75 group hover:bg-gray-700 text-white" %>
          </li>
          <li>
            <%= link_to "#", root_path, class: "flex items-center p-2 pl-11 w-full text-base font-normal rounded-lg transition duration-75 group hover:bg-gray-700 text-white" %>
          </li>
        </ul>
      </li>
      <li>
        <button type="button" class="flex items-center p-2 w-full text-base font-normal rounded-lg transition duration-75 group hover:bg-gray-700 text-white aria-controls="dropdown-info" data-collapse-toggle="dropdown-info">
        <svg class="flex-shrink-0 w-6 h-6 text-gray-400 transition duration-75 group-hover:text-white" aria-hidden="true" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M2 5a2 2 0 012-2h8a2 2 0 012 2v10a2 2 0 002 2H4a2 2 0 01-2-2V5zm3 1h6v4H5V6zm6 6H5v2h6v-2z" clip-rule="evenodd"></path><path d="M15 7h1a2 2 0 012 2v5.5a1.5 1.5 0 01-3 0V7z"></path></svg>
        <span class="flex-1 ml-3 text-left whitespace-nowrap" sidebar-toggle-item="">Info</span>
        <svg sidebar-toggle-item="" class="w-6 h-6" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z" clip-rule="evenodd"></path></svg>
        </button>
        <ul id="dropdown-info" class="hidden py-2 space-y-2">
          <li>
            <%= link_to "Forum", forums_path, class: "flex items-center p-2 pl-11 w-full text-base font-normal rounded-lg transition duration-75 group hover:bg-gray-700 text-white" %>
          </li>
          <li>
            <%= link_to "News", news_index_path, class: "flex items-center p-2 pl-11 w-full text-base font-normal rounded-lg transition duration-75 group hover:bg-gray-700 text-white" %>
          </li>
          <li>
            <%= link_to "Articles", articles_path, class: "flex items-center p-2 pl-11 w-full text-base font-normal rounded-lg transition duration-75 group hover:bg-gray-700 text-white" %>
          </li>
          <li>
            <%= link_to "Ratings", root_path, class: "flex items-center p-2 pl-11 w-full text-base font-normal rounded-lg transition duration-75 group hover:bg-gray-700 text-white" %>
          </li>
        </ul>
      </li>
      <li>
        <%= link_to(rooms_path, class:"flex items-center p-2 text-base font-normal rounded-lg text-white hover:bg-gray-700") do %>
          <svg aria-hidden="true" class="flex-shrink-0 w-6 h-6 text-gray-500 transition duration-75 dark:text-gray-400 group-hover:text-gray-900 dark:group-hover:text-white" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path d="M7 3a1 1 0 000 2h6a1 1 0 100-2H7zM4 7a1 1 0 011-1h10a1 1 0 110 2H5a1 1 0 01-1-1zM2 11a2 2 0 012-2h12a2 2 0 012 2v4a2 2 0 01-2 2H4a2 2 0 01-2-2v-4z"></path></svg>
          <span class="ml-3">Messages</span>
        <% end %>
      </li>
      <li>
        <%= link_to(root_path, class:"flex items-center p-2 text-base font-normal rounded-lg text-white hover:bg-gray-700") do %>
          <svg aria-hidden="true" class="flex-shrink-0 w-6 h-6 text-gray-400 transition duration-75 group-hover:text-white" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M10 2a4 4 0 00-4 4v1H5a1 1 0 00-.994.89l-1 9A1 1 0 004 18h12a1 1 0 00.994-1.11l-1-9A1 1 0 0015 7h-1V6a4 4 0 00-4-4zm2 5V6a2 2 0 10-4 0v1h4zm-6 3a1 1 0 112 0 1 1 0 01-2 0zm7-1a1 1 0 100 2 1 1 0 000-2z" clip-rule="evenodd"></path></svg>
          <span class="flex-1 ml-3 whitespace-nowrap">Investments</span>
        <% end %>
      </li>
      <li>
        <%= link_to(root_path, class:"flex items-center p-2 text-base font-normal rounded-lg text-white hover:bg-gray-700") do %>
          <svg aria-hidden="true" class="flex-shrink-0 w-6 h-6 text-gray-500 transition duration-75 dark:text-gray-400 group-hover:text-gray-900 dark:group-hover:text-white" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path d="M5 3a2 2 0 00-2 2v2a2 2 0 002 2h2a2 2 0 002-2V5a2 2 0 00-2-2H5zM5 11a2 2 0 00-2 2v2a2 2 0 002 2h2a2 2 0 002-2v-2a2 2 0 00-2-2H5zM11 5a2 2 0 012-2h2a2 2 0 012 2v2a2 2 0 01-2 2h-2a2 2 0 01-2-2V5zM11 13a2 2 0 012-2h2a2 2 0 012 2v2a2 2 0 01-2 2h-2a2 2 0 01-2-2v-2z"></path></svg>
          <span class="flex-1 ml-3 whitespace-nowrap">Events</span>
        <% end %>
      </li>
      <li>
        <%= link_to(root_path, class:"flex items-center p-2 text-base font-normal rounded-lg text-white hover:bg-gray-700") do %>
          <svg aria-hidden="true" class="flex-shrink-0 w-5 h-5 text-gray-500 transition duration-75 group-hover:text-gray-900 dark:group-hover:text-white dark:text-gray-400" focusable="false" data-prefix="fas" data-icon="gem" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><path fill="currentColor" d="M378.7 32H133.3L256 182.7L378.7 32zM512 192l-107.4-141.3L289.6 192H512zM107.4 50.67L0 192h222.4L107.4 50.67zM244.3 474.9C247.3 478.2 251.6 480 256 480s8.653-1.828 11.67-5.062L510.6 224H1.365L244.3 474.9z"></path></svg>
          <span class="flex-1 ml-3 whitespace-nowrap">Courses</span>
        <% end %>
      </li>
      <li>
        <%= link_to(root_path, class:"flex items-center p-2 text-base font-normal rounded-lg text-white hover:bg-gray-700") do %>
          <svg aria-hidden="true" class="flex-shrink-0 w-6 h-6 text-gray-400 transition duration-75 group-hover:text-white" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M5 4a3 3 0 00-3 3v6a3 3 0 003 3h10a3 3 0 003-3V7a3 3 0 00-3-3H5zm-1 9v-1h5v2H5a1 1 0 01-1-1zm7 1h4a1 1 0 001-1v-1h-5v2zm0-4h5V8h-5v2zM9 8H4v2h5V8z" clip-rule="evenodd"></path></svg>
          <span class="flex-1 ml-3 whitespace-nowrap">Financial calculator</span>
        <% end %>
      </li>
      <li>
        <%= link_to(edit_user_registration_path, class: "flex items-center p-2 text-base font-normal rounded-lg text-white hover:bg-gray-700") do %>
          <svg class="flex-shrink-0 w-6 h-6 text-gray-400 transition duration-75 group-hover:text-white" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="3"></circle><path d="M19.4 15a1.65 1.65 0 0 0 .33 1.82l.06.06a2 2 0 0 1 0 2.83 2 2 0 0 1-2.83 0l-.06-.06a1.65 1.65 0 0 0-1.82-.33 1.65 1.65 0 0 0-1 1.51V21a2 2 0 0 1-2 2 2 2 0 0 1-2-2v-.09A1.65 1.65 0 0 0 9 19.4a1.65 1.65 0 0 0-1.82.33l-.06.06a2 2 0 0 1-2.83 0 2 2 0 0 1 0-2.83l.06-.06a1.65 1.65 0 0 0 .33-1.82 1.65 1.65 0 0 0-1.51-1H3a2 2 0 0 1-2-2 2 2 0 0 1 2-2h.09A1.65 1.65 0 0 0 4.6 9a1.65 1.65 0 0 0-.33-1.82l-.06-.06a2 2 0 0 1 0-2.83 2 2 0 0 1 2.83 0l.06.06a1.65 1.65 0 0 0 1.82.33H9a1.65 1.65 0 0 0 1-1.51V3a2 2 0 0 1 2-2 2 2 0 0 1 2 2v.09a1.65 1.65 0 0 0 1 1.51 1.65 1.65 0 0 0 1.82-.33l.06-.06a2 2 0 0 1 2.83 0 2 2 0 0 1 0 2.83l-.06.06a1.65 1.65 0 0 0-.33 1.82V9a1.65 1.65 0 0 0 1.51 1H21a2 2 0 0 1 2 2 2 2 0 0 1-2 2h-.09a1.65 1.65 0 0 0-1.51 1z"></path></svg>
          <span class="flex-1 ml-3 whitespace-nowrap">Settings</span>
        <% end %>
      </li>
      <li>
        <%= link_to(destroy_user_session_path, class:"flex items-center p-2 text-base font-normal rounded-lg text-white hover:bg-gray-700") do %>
          <svg class="flex-shrink-0 w-6 h-6 text-gray-400 transition duration-75 group-hover:text-white" xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M16 17l5-5-5-5M19.8 12H9M10 3H4v18h6"/></svg>
          <span class="flex-1 ml-3 whitespace-nowrap">Exit</span>
        <% end %>
      </li>
    </ul>
  </div>
</aside>
<script src="https://unpkg.com/flowbite@1.5.1/dist/flowbite.js"></script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>InvestProject2010</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <% if user_signed_in? %>
    <body class="bg-gray-800 flex">
      <aside class="w-64">
        <%= render "layouts/sidebar" %>
      </aside>
      <main class="w-5/6">
        <% if notice.present? %>
          <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
        <% end %>
        <p class="alert"><%= alert %></p>
        <%= yield %>
      </main>
    </body>
  <% else %>
    <body class="bg-gray-800">
      <%= render "layouts/header" %>
      <main>
        <% if notice.present? %>
          <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
        <% end %>
        <p class="alert"><%= alert %></p>
        <%= yield %>
      </main>
    </body>
  <% end %>
</html>